### ISSUE TITLE
json error with method POST and headers

### ISSUE THREAD

**Issue by yakir2b** [swisskyrepo/GraphQLmap#14]
Hi,

When i tried using it with the parameters  method=POST and headers like the example. i received this error-
AttributeError: 'NoneType' object has no attribute 'json' 

Tnx

**Comment by orangecms** [comment]
Can you post your full command line (just exchange your URL for example.com or something)?

I have tried this myself and it worked. :)

**Comment by marz-hunter** [comment]
Traceback (most recent call last):
  File "graphqlmap.py", line 75, in <module>
    GraphQLmap(args)
  File "graphqlmap.py", line 50, in __init__
    dump_schema(self.url, self.method, 15, self.headers)
  File "/root/GraphQLmap/attacks.py", line 31, in dump_schema
    schema = r.json()
AttributeError: 'NoneType' object has no attribute 'json'

**Comment by orangecms** [comment]
> Traceback (most recent call last):
> File "graphqlmap.py", line 75, in
> GraphQLmap(args)
> File "graphqlmap.py", line 50, in **init**
> dump_schema(self.url, self.method, 15, self.headers)
> File "/root/GraphQLmap/attacks.py", line 31, in dump_schema
> schema = r.json()
> AttributeError: 'NoneType' object has no attribute 'json'

That's the stack trace; what is the full command line that you entered?

**Comment by secjey** [comment]
Hi @yakir2b,

I believe you might want to take a look at @orangecms pull request #20 for JSON support. I had the same issue as you and this fixed it. Thanks @orangecms by the way!

**Comment by oscarsanden** [comment]
I got this error message too and I was missing `--json` in the command line.
