### ISSUE TITLE
Support Other Graphql Query Formats

### ISSUE THREAD

**Issue by uBadRequest** [swisskyrepo/GraphQLmap#18]
I have found alot of graphql servers take queries via post requests differently.

`{ "query": "{}", "variables": {} }`

This is the format that Shopify's graphql server supports. It has to be made as a post request to the /graphql endpoint. Would it be possible to support this query format?

**Comment by orangecms** [comment]
I have recently had that need as well; I'll publish my patch for that.

I would create another switch, maybe something like `--json` as a shorthand or something, so it would automatically send POST requests with the `Content-Type: application/json` header and the body encoded in JSON. The `variables` should be optional; the parameters can just be inlined with the tool.
