### ISSUE TITLE
Headers error "bearer"

### ISSUE THREAD

**Issue by cococookiehub** [swisskyrepo/GraphQLmap#25]
Hi! When using authentication token as per your example of usage I get the error that the Bearer is not a valid argument. I tried with single and double quotes but I get the same error. Any idea what´s going on?

this is your example:

python3 graphqlmap.py -u https://yourhostname.com/graphql -v --method POST --headers '{"Authorization" : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXh0Ijoibm8gc2VjcmV0cyBoZXJlID1QIn0.JqqdOesC-R4LtOS9H0y7bIq-M8AGYjK92x4K3hcBA6o"}'

**Comment by haybeseret** [comment]
same here  - did you managed to sort it  out ?
