### ISSUE TITLE
readline module is not available on Windows

### ISSUE THREAD

**Issue by trieulieuf9** [swisskyrepo/GraphQLmap#3]
your "import readline" does not work on Windows. I think this is the only library that keep graphqlmap from working cross-platform. Can we change "readline" to something else? which is available on Windows as well.

**Comment by swisskyrepo** [comment]
"readline" cannot be replaced as it will break the auto-completion which is one of the main features of this project. Unless you find a better alternative ;)

**Comment by fuomag9** [comment]
Fixed in 15c1afa5ecfce475f5e25030699aca85352e2fee
