### ISSUE TITLE
[!] Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by thomas-girard** [swisskyrepo/GraphQLmap#49]
![image](https://user-images.githubusercontent.com/70712826/213524933-31c1e84c-bc7c-45f1-b780-4ee5d6cddba1.png)

**Comment by Tanguy-Boisset** [comment]
The url you are using doesn't look like a GraphQL endpoint. Are you sure it's the right path ?
It's most of the time something like `http://example.com/graphql`

**Comment by thomas-girard** [comment]
Thanks a lot @Tanguy-Boisset !
