### ISSUE TITLE
issue while opening graphqlmap.py 

### ISSUE THREAD

**Issue by 0-0eth0** [swisskyrepo/GraphQLmap#7]
see the screenshot attached
![jinayss](https://user-images.githubusercontent.com/50541295/69423090-459f5680-0d4b-11ea-86d2-299b436a1f6b.png)

**Comment by Et0hacker** [comment]
> python3 graphqlmap.py -u https://app.pipefy.com/graphiql--method

   _____                 _      ____  _                            
  / ____|               | |    / __ \| |                           
 | |  __ _ __ __ _ _ __ | |__ | |  | | |     _ __ ___   __ _ _ __  
 | | |_ | '__/ _` | '_ \| '_ \| |  | | |    | '_ ` _ \ / _` | '_ \ 
 | |__| | | | (_| | |_) | | | | |__| | |____| | | | | | (_| | |_) |
  \_____|_|  \__,_| .__/|_| |_|\___\_\______|_| |_| |_|\__,_| .__/ 
                  | |                                       | |    
                  |_|                                       |_|    
                              Author: @pentest_swissky Version: 1.0 
GraphQLmap > dump_new
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "graphqlmap.py", line 71, in <module>
    GraphQLmap(args)
  File "graphqlmap.py", line 47, in __init__
    dump_schema(self.url, self.method, 15)
  File "/root/GraphQLmap/attacks.py", line 36, in dump_schema
    schema = r.json()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

> 

getting this error

**Comment by Et0hacker** [comment]
GraphQLmap > dump
dump
/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[!] Expecting value: line 1 column 1 (char 0)
GraphQLmap >

**Comment by samsayen** [comment]
Same issue as Et0hacker with the first character...
GraphQLmap > map
map
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[!] Expecting value: line 1 column 1 (char 0)

**Comment by fuomag9** [comment]
calling `export PYTHONWARNINGS="ignore:Unverified HTTPS request"` fixed it for me, but a code patch has to be done, I'll work on it later

**Comment by fuomag9** [comment]
Fixed in f0b190a86e9195d1612b79cc441b49733461f014

**Comment by orangecms** [comment]
Regarding the shebang, see https://github.com/swisskyrepo/GraphQLmap/pull/19 - that would fix it if you call the tool directly.
